### ISSUE TITLE
problems linking libxml2 to icu

### ISSUE THREAD

**Issue by amerb** [USGS-EROS/espa-product-formatter#50]
Issue:
I'm running into a problem correctly attributing environmental variables:
When I set it to:
export XML2INC="/home/.../anaconda2/envs/supp/include"
I receive the following:
espa_metadata.h:20:27: fatal error: libxml/parser.h: No such file or directory
#include <libxml/parser.h>

However, when I change it to to:
export XML2INC="/home/../anaconda2/envs/supp/include/libxml2"
I get the following compilation error
/home/.../anaconda2/envs/supp/include/libxml2/libxml/encoding.h:31:26: fatal error: unicode/ucnv.h: No such file or directory
#include <unicode/ucnv.h>

Am I missing something obvious here?

I'm working with libxml2-2.9.8

**Comment by gschmidt-usgs** [comment]
Our libxml environment variables are set to the following:
# add libxml2 libraries and includes
setenv XML2INC /data/cots/libxml2/include/libxml2
setenv XML2LIB /data/cots/libxml2/lib

Here is a listing of what our build has contained in the libxml directories:
bin:
xml2-config  xmlcatalog  xmllint

include:
libxml2

lib:
libxml2.a   libxml2.so    libxml2.so.2.9.1  xml2Conf.sh
libxml2.la  libxml2.so.2  pkgconfig

share:
aclocal  doc  gtk-doc  man


The libxml2 subdirectory contains a libxml directory, which then contains the following:
'ls include/libxml2/libxml'
c14n.h        list.h              tree.h         xmlregexp.h
catalog.h     nanoftp.h           uri.h          xmlsave.h
chvalid.h     nanohttp.h          valid.h        xmlschemas.h
debugXML.h    parser.h            xinclude.h     xmlschemastypes.h
dict.h        parserInternals.h   xlink.h        xmlstring.h
DOCBparser.h  pattern.h           xmlautomata.h  xmlunicode.h
encoding.h    relaxng.h           xmlerror.h     xmlversion.h
entities.h    SAX2.h              xmlexports.h   xmlwriter.h
globals.h     SAX.h               xmlIO.h        xpath.h
hash.h        schemasInternals.h  xmlmemory.h    xpathInternals.h
HTMLparser.h  schematron.h        xmlmodule.h    xpointer.h
HTMLtree.h    threads.h           xmlreader.h

**Comment by amerb** [comment]
Thanks for your response!  I was able to install libxml2-2.9.1 as a standalone package outside of conda and was able to load everything successfully.
